spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tp?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jpa:
    hibernate:
      ddl-auto: update
